START      = <WHITESPACE?> (NUMBER | SUM | DIFF | PROD) <WHITESPACE?>
SUM        = NUMBER <WHITESPACE?> <'+'> <WHITESPACE?> NUMBER
DIFF       = NUMBER <WHITESPACE?> <'-'> <WHITESPACE?> NUMBER
PROD       = NUMBER <WHITESPACE?> <'*'> <WHITESPACE?> NUMBER
NUMBER     = #'[-+]?[0-9]+'
WHITESPACE = #'[,\ \t]+'
