START      = <WHITESPACE?> (EXPR | SUM | DIFF | PROD) <WHITESPACE?>
<EXPR>     = SUM | DIFF | PROD | GROUP
<GROUP>    = NUMBER | <'('> <WHITESPACE?> EXPR <WHITESPACE?>  <')'>
SUM        = EXPR <WHITESPACE?> <'+'> <WHITESPACE?> GROUP
DIFF       = EXPR <WHITESPACE?> <'-'> <WHITESPACE?> GROUP
PROD       = EXPR <WHITESPACE?> <'*'> <WHITESPACE?> GROUP
NUMBER     = #'[-+]?[0-9]+'
WHITESPACE = #'[,\ \t]+'
